version: '3.3'

services:
  car-next:
    container_name: car-next
    restart: always
    image: node:20.10.0
    ports:
      - 4000:3000
    environment:
      - PORT=3000

    volumes:
      - ./:/usr/src/car-next
    working_dir: /usr/src/car-next

    networks:
      - client-network

    # FOR PRODUCTION

    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge

    # car-next: localhost:4000 - container:3000
    # car-api: localhost:4001 - container:3007
    # car-batch: localhost:4002 - container:3008
